#!/bin/bash
# requires: dcmtk, curl

session=visit1
USER=$1
PASSWORD=$2
PROJECT=$3
i=$4
DIR=$5
XNAT=http://10.63.183.85:8080/xnat


####currentdir=$(pwd)

###read -p "Usuário do XNAT:" USER
###read -s -p "Senha:" PASSWORD

# Create a session cookie, we want to re-use that session instead of providing
# login information every time. Number of sessions might be limited otherwise to 1000.
cookie=`curl -k -u $USER:$PASSWORD -X POST $XNAT/data/JSESSION`

###read -p "Nome do projeto:" PROJECT

  
  ######## Início da coleta de informações do cabeçalho DICOM ########
  
  cd $DIR/dicom/*
  imgdcm=$(ls MR* | tail -n 1 | cut -f 2 -d '/')
  
  agewithy=`dcmdump +P 0010,1010 $imgdcm +L | cut -f 2 -d '[' | cut -f 1 -d ']' | grep -E '[0-9]{1,4}'`
  age=${agewithy%?}
  weight=`dcmdump +P 0010,1030 $imgdcm +L | cut -f 2 -d '[' | cut -f 1 -d ']'`
  yob=`dcmdump +P 0010,0030 $imgdcm +L | cut -f 2 -d '[' | cut -f 1 -d ']' | cut -c 1-4`
  sex_dicom=`dcmdump +P 0010,0040 $imgdcm +L | cut -f 2 -d '[' | cut -f 1 -d ']'`

	if [ "$sex_dicom" = "M" ]; then	# Se estiver escrito M no cabeçalho, substitui por "male", se não substitui por "female"
	  sex_dicom=male
	elif [ "$sex_dicom" = "F" ]; then
	  sex_dicom=female
	else	
	  sex_dicom=unknown
	fi
	
	#for varint in age yob weight ; do #Testa se os valores são integers, caso não sejam os substituem com unknown
    	#  if ! [[ "${!varint}" =~ ^[0-9]+$ ]] ; then
       	#    declare $varint=unknown
    	#  fi
	#done
	

  ################ Fim da coleta das informações #####################

  #cd $currentdir
  #zip -r dicom dicom
  #rm -rv dicom
	
  cd $DIR
  #tar -zcvf dicom.tar.gz dicom
  zip -r dicom.zip dicom

echo
echo "###############################################"
echo "Session ID is: $cookie"
echo "###############################################"
echo

###read -p "Subject:" i

# create subject in case it does not exist
echo
echo "###########################"
echo "Criando subject $i"
echo "###########################"
echo

curl --cookie JSESSIONID=$cookie -k -X PUT "$XNAT/data/archive/projects/$PROJECT/subjects/$i?gender=$sex&age=$age&yob=$yob&weight=$weight"

# create session in case it does not exist
echo
echo "######################"
echo "Criando sessao $session"
echo "######################"
echo

curl --cookie JSESSIONID=$cookie -k -X PUT $XNAT/data/archive/projects/$PROJECT/subjects/$i/experiments/${i}_${session}?xsiType=xnat:mrSessionData
#curl --cookie JSESSIONID=$cookie -k -X PUT $XNAT/data/archive/projects/$PROJECT/subjects/$i/experiments/${i}_${session}?visit_id=$session 

echo
echo "##############"
echo "Enviando DICOM"
echo "##############"
echo

curl --cookie JSESSIONID=$cookie --data-binary @"dicom.zip" -H 'Content-Type: application/zip' $XNAT/data/services/import?import-handler=DICOM-zip\&PROJECT_ID=$PROJECT\&SUBJECT_ID=$i\&EXPT_LABEL=${i}_${session}\&overwrite=append\&prearchive=true&inbody=true

#rm -v dicom.zip

echo
echo "#############################"	
echo "Concluído subject $i"
echo "#############################"
echo	
echo Aguarde...
timecount(){
        min=0
        sec=10
        while [ $min -ge 0 ]; do
                while [ $sec -ge 0 ]; do
                        echo -ne "00:0$min:$sec\033[0K\r"
                        sec=$((sec-1))
                        sleep 1
                done
                sec=59
                min=$((min-1))
        done
}
timecount

cd $DIR
###cd $currentdir

#echo "$subject $session done"
